# Generated by Django 2.1.3 on 2018-12-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
